import { I } from '../../core/utils.js';
import { Store } from '../../core/store.js';
import { T } from '../../data/domain.js';
import { dn } from '../../components/DriverShell.jsx';

/* ---------- S2 · reference issued ---------- */

const WHO_ISSUES_NOTE =
  'The reference is generated by <b>the insurer</b>, client-side, from a format the insurer owns ' +
  '&mdash; <code>INS-DE-YYYY-NNNNNN</code>. It does not wait on the TPA, and offline it is ' +
  'produced <b>on the phone</b> with no round trip at all. If the claim reference can only come ' +
  "back from the TPA, then the TPA&rsquo;s uptime is the driver&rsquo;s problem and the insurer " +
  'has outsourced its own moment of truth. Flip <b>TPA down</b> and this screen does not change ' +
  'by one pixel.';

const COVERAGE_NOTE =
  'The coverage check just failed &mdash; this vehicle is not on the policy schedule for ' +
  "today&rsquo;s date. The driver&rsquo;s screen is <b>identical</b>: reference issued, recovery " +
  'dispatched, no warning, no delay. The flag went to the underwriting queue as a human review ' +
  'task. Auto-rejecting at the roadside would be an automated adverse decision on an individual, ' +
  'which under <b>Art. 22</b> needs human involvement and a right to contest &mdash; and it would ' +
  'be operationally wrong anyway, because schedule data is stale more often than drivers are ' +
  'dishonest.';

const TPA_DOWN_NOTE =
  'Nothing on this screen knows that. The incident was accepted, persisted and acknowledged; the ' +
  'forward to the TPA is queued behind exponential backoff. <b>Accept &rarr; persist &rarr; ' +
  'acknowledge &rarr; forward async.</b> Watch the retries in the System pane.';

export function scrReference() {
  const s = Store.s;
  const d = s.draft;
  const secs = s.stoppedAt && s.startedAt
    ? ((s.stoppedAt - s.startedAt) / 1000).toFixed(1)
    : null;

  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
      <div className="scroll">
        <div className="pad" style={{ paddingTop: '20px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <span style={{ color: 'var(--ok)' }} dangerouslySetInnerHTML={{ __html: I.chk }} />
            <span style={{ fontWeight: 700, color: 'var(--ok)', fontSize: '14px' }}>
              {T('refTitle')}
            </span>
          </div>

          <div className="sp16" />

          <div className="ref-hero">
            <div
              className="tiny"
              style={{
                letterSpacing: '.09em', textTransform: 'uppercase',
                fontSize: '10.5px', color: 'var(--ink-2)',
              }}
            >
              Your reference
            </div>
            <div className="ref-code">{s.reference || '…'}</div>

            <button
              className="btn btn-secondary btn-sm"
              data-act="copy-ref"
              style={{ margin: '10px auto 0' }}
            >
              <span dangerouslySetInnerHTML={{ __html: I.copy }} />
              Copy
            </button>

            <div className="ref-stamp">
              <span dangerouslySetInnerHTML={{ __html: I.shield }} />
              issued by the insurer — independent of the TPA
            </div>

            <div style={{ marginTop: '10px' }}>
              <span className="ref-latency">
                {s.fail.offline
                  ? 'generated on this phone · 0 ms'
                  : `issued in ${s.refLatencyMs || 42} ms`}
              </span>
            </div>
          </div>

          <div className="sp16" />
          <p className="sub" style={{ fontSize: '15px' }}>
            Give this number to the police officer and the other driver. It is already valid.
          </p>

          {dn('Who issues the reference is a commercial question, not a technical one', WHO_ISSUES_NOTE)}

          {d.drivable === false && (
            <>
              <div className="sp16" />
              <div className="card" style={{ borderColor: '#c3d6cd', background: 'var(--accent-soft)' }}>
                <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
                  <span
                    style={{ color: 'var(--accent)', flex: 'none', marginTop: '2px' }}
                    dangerouslySetInnerHTML={{ __html: I.truck }}
                  />
                  <div>
                    <div style={{ fontWeight: 700, fontSize: '15.5px' }}>
                      Dispatch notified · they arrange recovery
                    </div>
                    <p className="tiny" style={{ marginTop: '4px' }}>
                      Anja at dispatch has it and is arranging a truck. She will call you. Stay behind the barrier.
                    </p>
                    <div className="chip warn" style={{ marginTop: '9px', fontSize: '10px' }}>
                      SIMULATED — no recovery provider was contacted
                    </div>
                  </div>
                </div>
              </div>
            </>
          )}

          {s.incident?.coverage_status === 'disputed'
            && dn('What the driver does NOT see', COVERAGE_NOTE)}

          {s.fail.tpa && dn('The TPA is down right now', TPA_DOWN_NOTE)}

          <div className="sp16" />
          <div className="card-quiet">
            <div style={{ display: 'flex', gap: '10px' }}>
              <span
                style={{ color: 'var(--ink-3)', flex: 'none', marginTop: '2px' }}
                dangerouslySetInnerHTML={{ __html: I.info }}
              />
              <p className="tiny" style={{ lineHeight: 1.5 }}>
                You can close the app now. Everything is saved. We&rsquo;ll message you a link to
                finish the rest whenever you&rsquo;re ready —{' '}
                <b style={{ color: 'var(--ink-2)' }}>the report is already filed</b>.
              </p>
            </div>
          </div>

          <div className="sp28" />
        </div>
      </div>

      <div className="dock">
        {secs && (
          <div style={{ textAlign: 'center', marginBottom: '10px' }}>
            <span
              className={`chip ${parseFloat(secs) <= 90 ? 'ok' : 'warn'}`}
              style={{ fontSize: '11px' }}
            >
              Blocking path complete in {secs}s
            </span>
          </div>
        )}
        <button className="btn btn-primary btn-lg" data-act="go-gaps">
          A few things that disappear if we wait
        </button>
        <button className="btn btn-quiet" data-act="finish-now">I&rsquo;m done for now</button>
      </div>
    </div>
  );
}
