import { I, el } from '../../core/dom.js';
import { Store } from '../../core/store.js';
import { T } from '../../data/domain.js';
import { dn } from '../../components/DriverShell.js';

/* ---------- S2 · reference issued ---------- */
export function scrReference(){
  const s=Store.s, d=s.draft;
  const wrap=el("div",{class:"scroll"});
  const inner=el("div",{class:"pad",style:"padding-top:20px"});

  const secs = s.stoppedAt && s.startedAt ? ((s.stoppedAt-s.startedAt)/1000).toFixed(1) : null;

  inner.append(el("div",{style:"display:flex;align-items:center;gap:10px"},
    el("span",{html:I.chk,style:"color:var(--ok)"}),
    el("span",{style:"font-weight:700;color:var(--ok);font-size:14px",text:T("refTitle")})
  ));
  inner.append(el("div",{class:"sp16"}));

  inner.append(el("div",{class:"ref-hero"},
    el("div",{class:"tiny",style:"letter-spacing:.09em;text-transform:uppercase;font-size:10.5px;color:#8fbdea",text:"Your reference"}),
    el("div",{class:"ref-code",text:s.reference||"…"}),
    el("button",{class:"btn btn-secondary btn-sm","data-act":"copy-ref",style:"margin:10px auto 0"},
      el("span",{html:I.copy}),"Copy"),
    el("div",{class:"ref-stamp"},el("span",{html:I.shield}),"issued by the insurer — independent of the TPA"),
    el("div",{style:"margin-top:10px"},
      el("span",{class:"ref-latency",text:(s.fail.offline?"generated on this phone · 0 ms":"issued in "+(s.refLatencyMs||42)+" ms")}))
  ));

  inner.append(el("div",{class:"sp16"}));
  inner.append(el("p",{class:"sub",style:"font-size:15px",
    text:"Give this number to the police officer and the other driver. It is already valid."}));

  inner.append(dn("Who issues the reference is a commercial question, not a technical one",
    "The reference is generated by <b>the insurer</b>, client-side, from a format the insurer owns — <code>INS-DE-YYYY-NNNNNN</code>. It does not wait on the TPA, and offline it is produced <b>on the phone</b> with no round trip at all. If the claim reference can only come back from the TPA, then the TPA's uptime is the driver's problem and the insurer has outsourced its own moment of truth. Flip <b>TPA down</b> and this screen does not change by one pixel."));

  if(d.drivable===false){
    inner.append(el("div",{class:"sp16"}));
    inner.append(el("div",{class:"card",style:"border-color:#c3d6cd;background:linear-gradient(160deg,#12233a,#101720)"},
      el("div",{style:"display:flex;gap:12px;align-items:flex-start"},
        el("span",{html:I.truck,style:"color:var(--accent);flex:none;margin-top:2px"}),
        el("div",{},
          el("div",{style:"font-weight:700;font-size:15.5px",text:"Recovery dispatched · ETA 45 min"}),
          el("p",{class:"tiny",style:"margin-top:4px",text:"Anja at dispatch has been notified. Stay behind the barrier."}),
          el("div",{class:"chip warn",style:"margin-top:9px;font-size:10px"},"SIMULATED — no recovery provider was contacted")
        ))
    ));
  }

  if(s.incident && s.incident.coverage_status==="disputed"){
    inner.append(dn("What the driver does NOT see",
      "The coverage check just failed — this vehicle is not on the policy schedule for today's date. The driver's screen is <b>identical</b>: reference issued, recovery dispatched, no warning, no delay. The flag went to the underwriting queue as a human review task. Auto-rejecting at the roadside would be an automated adverse decision on an individual, which under <b>Art. 22</b> needs human involvement and a right to contest — and it would be operationally wrong anyway, because schedule data is stale more often than drivers are dishonest."));
  }

  if(s.fail.tpa){
    inner.append(dn("The TPA is down right now",
      "Nothing on this screen knows that. The incident was accepted, persisted and acknowledged; the forward to the TPA is queued behind exponential backoff. <b>Accept → persist → acknowledge → forward async.</b> Watch the retries in the System pane."));
  }

  inner.append(el("div",{class:"sp16"}));
  inner.append(el("div",{class:"card-quiet"},
    el("div",{style:"display:flex;gap:10px"},
      el("span",{html:I.info,style:"color:var(--ink-3);flex:none;margin-top:2px"}),
      el("p",{class:"tiny",style:"line-height:1.5",html:"You can close the app now. Everything is saved. We'll message you a link to finish the rest whenever you're ready — <b style='color:var(--ink-2)'>the report is already filed</b>."}))
  ));

  inner.append(el("div",{class:"sp28"}));
  wrap.append(inner);

  const dock=el("div",{class:"dock"});
  if(secs) dock.append(el("div",{style:"text-align:center;margin-bottom:10px"},
    el("span",{class:"chip "+(parseFloat(secs)<=90?"ok":"warn"),style:"font-size:11px"},
      "Blocking path complete in "+secs+"s")));
  dock.append(el("button",{class:"btn btn-primary btn-lg","data-act":"go-gaps"},"A few things that disappear if we wait"));
  dock.append(el("button",{class:"btn btn-quiet","data-act":"finish-now"},"I'm done for now"));
  return el("div",{style:"flex:1;display:flex;flex-direction:column;overflow:hidden"},wrap,dock);
}


